### ISSUE TITLE
Send limit of 402.75 cac at a time

### ISSUE THREAD

**Issue by rocketeeer** [Cactus-Network/cactus-blockchain#12]
Cactus version: 1.21.dev1

Error occurs when sending more than 402750000000000 (402.75 cac) mojo in a single transaction:

`Submitting transaction... Exception from 'wallet' {'error': "Can't send more than 402750000000000 in a single transaction", 'success': False}`

**Comment by dominick01234** [comment]
This error occurs if you are trying to send more CAC than you have in your wallet. Thank you
