### ISSUE TITLE
Windows build

### ISSUE THREAD

**Issue by ageorge95** [Cactus-Network/cactus-blockchain#13]
When will the build for Windows be released ?

**Comment by dominick01234** [comment]
Windows build is available at Cactus-Network.net. Thank you

**Comment by ageorge95** [comment]
Hello, Thanks for your answer 👍

Will the windows build be added to assets in the future ?

**Comment by dominick01234** [comment]
Yes absolutely! Much more to come :) Thanks for asking. Feedback and
suggestions are always welcomed.

Please check out our Discord channel here:
https://discord.gg/jDZyHaeQJe
