### ISSUE TITLE
Support NFT plotters

### ISSUE THREAD

**Issue by arturotrenard** [Cactus-Network/cactus-blockchain#15]
Hello I am starting to cultivate with you and I won a test and only received 25% of my reward so I wanted to know when you plan to give 100% support to the NFT plots and my profits and those of all of us in the group are reduced to 25 % for having the NFT ploters. Thank you

**Comment by wrjmhb21** [comment]
Would like NFT plots be supported ASAP!

**Comment by dominick01234** [comment]
NFT Plots are supported. However you need to run the Cactus fd-cli tool to
recover your rewards from your XCH Singleton that you created in Chia.

So you rewards are always yours, but you have to claim them. Eventually
this will be built into a newer Cactus version.

**Comment by dominick01234** [comment]
NFT Plots are supported. However you need to run the Cactus fd-cli tool to
recover your rewards from your XCH Singleton that you created in Chia.

So you rewards are always yours, but you have to claim them. Eventually
this will be built into a newer Cactus version.

**Comment by stanchiam** [comment]
A new network transaction has been sent to recover a total of 87.500000000000 coins.
    A new network transaction has been sent to recover a total of 26.250000000000 coins.

    Sent transactions to recover a total of 113.750000000000 coins.
    Coins should be spendable in few network confirmations.

Coins recovered but not sent to wallet. Is there bug in the fd-cli?
Is the cactus fd-cli same as the flora? tried both, same result, coins recovered but not updated to wallet

**Comment by stanchiam** [comment]
> ```
> A new network transaction has been sent to recover a total of 87.500000000000 coins.
> A new network transaction has been sent to recover a total of 26.250000000000 coins.
> 
> Sent transactions to recover a total of 113.750000000000 coins.
> Coins should be spendable in few network confirmations.
> ```
> 
> Coins recovered but not sent to wallet. Is there bug in the fd-cli?
> Is the cactus fd-cli same as the flora? tried both, same result, coins recovered but not updated to wallet

nvm, it took few hours for wallet to update, others seems to be instant

**Comment by dominick01234** [comment]
Full Cactus Coin recovery has been implemented using the 'fd-cli' coin recovery tool. You can either use the Cactus version, or I believe the Flora version now works for all forks including Cactus. The Cactus version has been tested and confirmed to fully recover Pool Rewards from your NFT. Please use our Discord if you have issues. Thanks
