### ISSUE TITLE
Failing to import mnemonic

### ISSUE THREAD

**Issue by HealthBar-hub** [Cactus-Network/cactus-blockchain#2]
Cactus CLI self compiled fails to accept certain words from chia mnemonics - making some plots unfarmable

**Comment by dominick01234** [comment]
I did not see this issue

**Comment by HealthBar-hub** [comment]
singles out 'exchange' as being mispelled

**Comment by HealthBar-hub** [comment]
"exchange is not in the mnemonic dictionary; may be misspelled"
