### ISSUE TITLE
[BUG]With Update to latest version mnemonic doesnt work

### ISSUE THREAD

**Issue by johnnyde94** [Cactus-Network/cactus-blockchain#28]
With Update to the latest version mnemonic doesn't work as it is saying the word exchange is not in the dictionary.

**Comment by johnnyde94** [comment]
I know you can fix it by editing the language file i think it is called, the file with the list of names in it possible to be used as a keyphrase. i just cant remember where that file is located

**Comment by johnnyde94** [comment]
it is the english.text file located at C:\Users\johnn\AppData\Local\cactus-blockchain\app-1.2.11\resources\app.asar.unpacked\daemon\cactus\util  exchange is spelled as "ecacange" there

**Comment by dominick01234** [comment]
Thanks Johnny. I’ll make that update today. Appreciate the note.

**Comment by johnnyde94** [comment]
NP happy to help!

 

Thank You,

John DeLuca

**Comment by dominick01234** [comment]
Bug fixed.
