### ISSUE TITLE
Failure to connect to RPC Port

### ISSUE THREAD

**Issue by 13thProgression** [Cactus-Network/cactus-blockchain#4]
When trying to query the chain via the RPC interface, I get an SSL error reported.  Don't see with other forks.

[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain

**Comment by dominick01234** [comment]
Please let the node introducer run longer to connect with Nodes that are on the new SSL, or use the Node List at Cactus-Network.net. Thank you.
