### ISSUE TITLE
Mnemonics affected by blanket changing "xch" to "cac"

### ISSUE THREAD

**Issue by HealthBar-hub** [Cactus-Network/cactus-blockchain#8]
The mnemonic word "exchange" is no longer accepted when attempting to add keys.

This is due to the word being modified within the mnemonic dictionary, to "ecacange" (xch > cac) - seems like this has been done with a simple blanket find-and-replace

entering ecacange when adding keys will still build a private key, but the fingerprint will be different and it will fail to register plots being added

**Comment by Jsewill** [comment]
In ./cactus/util/english.txt

**Comment by dominick01234** [comment]
Fixed in new commit
