### ISSUE TITLE
plots with missing keys.....[Bug] 

### ISSUE THREAD

**Issue by darwinjobchia** [Cactus-Network/cactus-blockchain#90]
### What happened?

with latest version, plots with missing keys, cant farm
![chia](https://user-images.githubusercontent.com/83147673/210349792-940af0f9-4967-4d71-818d-4b8f550e0cbe.JPG)

### Version

1.61  1.52

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by dominick01234** [comment]
I can not reproduce this issue. Please ask for help on the discord channel: https://discord.gg/qfHBqZnXTj

Thank you! Dommer
