### ISSUE TITLE
[Bug] 1.6.2 Linux CLI install - pip refers to path "/home/sgrowies"

### ISSUE THREAD

**Issue by guydavis** [Cactus-Network/cactus-blockchain#93]
### What happened?

Thanks for the Cactus 1.6.2 release.  I noticed there may be a path hard-coded to your local system in the pip config?  Here's what I am seeing.  Is `/home/xxxxxxx a path on your development system? 

### Version

1.6.2 (1999f8921050bd034b7af46f665e5d268cfb397d)

### What platform are you using?

Linux

### What ui mode are you using?

CLI

### Relevant log output

```shell
root@aragorn:~# docker exec -it machinaris-cactus bash
root@aragorn:/cactus-blockchain# ./venv/bin/cactus version
1.6.2
root@aragorn:/cactus-blockchain# git rev-parse --verify HEAD
1999f8921050bd034b7af46f665e5d268cfb397d
root@aragorn:/cactus-blockchain# ./venv/bin/pip3 install requests
bash: ./venv/bin/pip3: /home/xxxxx/cactus-blockchain/venv/bin/python: bad interpreter: No such file or directory
root@aragorn:/cactus-blockchain#
```

**Comment by jfikar** [comment]
I hit the same problem. It seems it is related to python vs. python3. Installing a package python-is-python3 on Debian and Ubuntu solves the problem for now.

**Comment by guydavis** [comment]
> I hit the same problem. It seems it is related to python vs. python3. Installing a package python-is-python3 on Debian and Ubuntu solves the problem for now.

Hmm, thanks for the tip.  Doesn't seem to work in my case as was already installed on Ubuntu 22.04 (Jammy).  

EDIT: I should mention more clearly, this is all within a Docker image.  I'm not managing an install on the Host OS.  This is built once into an image, then entirely discarded for a fresh image build when the next Cactus version comes out.

**Comment by dominick01234** [comment]
It appears it is a virtual environment issue. Try this: "pip install -U --force-reinstall virtualenv" or "pip uninstall virtualenv && pip install virtualenv"

https://stackoverflow.com/questions/53863459/virtualenv-error-bad-interpreter-no-such-file-or-directory

**Comment by guydavis** [comment]
Thanks.  I found the [file with the hard-coded path](https://github.com/Cactus-Network/cactus-blockchain/blob/1999f8921050bd034b7af46f665e5d268cfb397d/venv/bin/pip3#L1).  

Would it be possible to not include the venv in the repository here, similar to how the parent Chia repository does it?

**Comment by dominick01234** [comment]
Good catch! For some reason gitignore didn't ignore the venv folder during this new release. I have made the corrections. Thank you!

**Comment by jfikar** [comment]
> > I hit the same problem. It seems it is related to python vs. python3. Installing a package python-is-python3 on Debian and Ubuntu solves the problem for now.
> 
> Hmm, thanks for the tip. Doesn't seem to work in my case as was already installed on Ubuntu 22.04 (Jammy).

You need to delete the venv folder and run sh ./install.sh again after installing python-is-python3. But I think the problem was solved meanwhile.
