### ISSUE TITLE
[Bug] Cactus shares all Ports with Silicon (SIT) Project 

### ISSUE THREAD

**Issue by Jared-woodruff** [Cactus-Network/cactus-blockchain#94]
### What happened?

All the ports for this fork of Chia conflict with another project started 2 years ago (Silicon SIT).

### Version

1.6.2

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by dominick01234** [comment]
This is not a bug of the Cactus Blockchain. Cactus Blockchain was started prior to Silicoin SIT and this issue arose during their launch and during the Silicoin forks lifetime. Anyone that wants to Farm Silicoin or any other Chia Fork that  has Port conflicts with the Cactus Blockchain, will have to change one of the Forks Ports in the config.yaml file. I would suggest not farming a Fork such as Silicoin that has both conflicts with Cactus and is not maintained (SIT github code last updated Feb 20, 2022).
